[package]
name = "sandbox"
version = "0.1.0"
authors = ["Michael Davidsaver <mdavidsaver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.53"

[dependencies]
libc = "0.2"
fork = "0.1"
signal-hook = "0.1"
log = { version = "0.4", features = ["std"] }
env_logger = "0.7"
